Traceback (most recent call last):
  File "C:\Users\staci\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "C:\Users\staci\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\staci\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\staci\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\staci\anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\staci\anaconda3\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\staci\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\staci\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
path = "./monet/"
file_list = os.listdir(path)
image_list = list()
c1 = 0 # Counter for Image Viewing
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_10908\1538703347.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mpath[0m [1;33m=[0m [1;34m"./monet/"[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mfile_list[0m [1;33m=[0m [0mos[0m[1;33m.[0m[0mlistdir[0m[1;33m([0m[0mpath[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mimage_list[0m [1;33m=[0m [0mlist[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mc1[0m [1;33m=[0m [1;36m0[0m [1;31m# Counter for Image Viewing[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [WinError 3] The system cannot find the path specified: './monet/'
FileNotFoundError: [WinError 3] The system cannot find the path specified: './monet/'

